### ISSUE TITLE
local web server is not working

### ISSUE THREAD

**Issue by ownport** [intropro/hadoop-env-config#4]

**Comment by ddenyshchenko** [comment]
``` python
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "./hadoop-env-config/__main__.py", line 73, in <module>
NameError: name 'SETTINGS' is not defined
```
